openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
  - name: Api-docs
    description: Api-docs operations.
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw-mongodb-ykgo.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      security: []
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      security: []
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/reset-pwd.yaml
  /auth/get-oauth-url:
    get:
      security: []
      $ref: ../swagger/paths/auth/get-oauth-url.yaml
  /auth/confirm-oauth:
    post:
      security: []
      $ref: ../swagger/paths/auth/confirm-oauth.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
